//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовой_проект_3._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamApps
    {
        public int Id { get; set; }
        public int FK_Team_Id { get; set; }
        public string Title { get; set; }
        public string AppText { get; set; }
        public System.DateTime AppDate { get; set; }
    
        public virtual Teams Teams { get; set; }
    }
}
